class InsertDefaultPageSections < ActiveRecord::Migration
  def self.up
    PageSection.create(:title => "Custom Content Theme1", :display_name => "Custom_Content_Theme1",:content => "<div id=\"display\">\r\n<div id=\"displayleft\">&nbsp;</div>\r\n<div id=\"displayright\">&nbsp;</div>\r\n<div id=\"displaymid\">\r\n<div id=\"shell\">\r\n<div id=\"i1\">\r\n<div class=\"controlpanel\"><img src=\"images/ejoshweb1/image1.png\" border=\"0\" /></div>\r\n<br /> Have your own <br /> control panel</div>\r\n<div id=\"i2\">\r\n<div class=\"colors\"><img src=\"images/ejoshweb1/image2.png\" border=\"0\" /></div>\r\n<br /> Customize<br /> using your own <br /> colors</div>\r\n<div id=\"i3\">\r\n<div class=\"layouts\"><img src=\"images/ejoshweb1/image3.png\" border=\"0\" /></div>\r\n<br />\r\n<div class=\"mar\">Customize using  <br /> your own  layouts</div>\r\n</div>\r\n<div id=\"i4\">\r\n<div class=\"plugin\"><img src=\"images/ejoshweb1/image4.png\" border=\"0\" /></div>\r\n<br />\r\n<div class=\"mar1\">Plug-in your <br />customized<br /> Applications</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>", :is_processing_reqd => false)

    PageSection.create(:display_name => "what_is_ejosh", :title => "what is ejosh", :content => "<p><img src=\"/system/images/1/small_thumb/question.jpg\" border=\"0\" alt=\"image\" width=\"50\" height=\"48\" style=\"float: left;\" /><span style=\"color: #888888; font-size: small;\"><strong></strong></span></p>\r\n<p>&nbsp;</p>\r\n<p><span style=\"color: #888888; font-size: small;\"><strong><span class=\"title\">What is eJosh All About ?</span></strong></span></p>\r\n<p>&nbsp;</p>\r\n<p>Lorem ipsum\r\ndolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh\r\neuismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut\r\nwisi enim ad minim veniam, quis nostrud exerci tation ullamcorper\r\nsuscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem\r\nvel eum iriure dolor in hendrerit in vulputate velit esse molestie\r\nconsequat, vel illum dolore eu feugiat nulla facilisis at vero eros et\r\naccumsan et iusto odio dignissim qui blandit praesent</p>\r\n<p>&nbsp;</p>\r\n<p>&nbsp;</p>\r\n<p>&nbsp;</p>", :is_processing_reqd => false)

    PageSection.create(:display_name => "who_uses_ejosh", :title => "who uses ejosh", :content => "<p><img src=\"/system/images/2/small_thumb/user.jpg\" border=\"0\" alt=\"image\" width=\"49\" height=\"50\" style=\"float: left;\" /></p>\r\n<p>&nbsp;</p>\r\n<p><span style=\"font-size: small;\"><strong><font style=\"color: #888888;\" color=\"#888888\"><span class=\"title\">Who Uses eJosh ?</span></font></strong></span></p>\r\n<p><br /> Lorem ipsum dolor sit\r\namet, consectetuer adipiscing elit, sed diam nonummy nibh euismod\r\ntincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim\r\nad minim veniam, quis nostrud exerci tation ullamcorper suscipit\r\nlobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum\r\niriure dolor in hendrerit in vulputate velit esse molestie consequat,\r\nvel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et\r\niusto odio dignissim qui blandit praesent</p>", :is_processing_reqd => false)

    PageSection.create(:display_name => "easy_to_use", :title => "easy to use", :content => "<p><img src=\"/system/images/3/small_thumb/easy.jpg\" border=\"0\" alt=\"image\" width=\"33\" height=\"35\" style=\"float: left;\" /><span style=\"color: #888888; font-size: small;\"><strong></strong></span></p>\r\n<p><span style=\"color: #888888; font-size: x-small;\"><strong><span class=\"title\">eJosh Is Easy To Use</span></strong></span></p>\r\n<div class=\"space\"><br /></div>\r\n<div class=\"space\"><br /></div>\r\n<div class=\"space\">Lorem\r\nipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy\r\nnibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.\r\nUt wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper\r\nsuscipit Ut wisi. Ut wisi enim ad minim veniam.</div>", :is_processing_reqd => false)

    PageSection.create(:display_name => "easy_to_customize", :title => "easy to customize", :content => "<p><img src=\"/system/images/4/small_thumb/tools.jpg\" border=\"0\" alt=\"image\" width=\"38\" height=\"37\" style=\"float: left;\" /><span style=\"color: #888888; font-size: x-small;\"><strong></strong></span></p>\r\n<p><span style=\"color: #888888; font-size: x-small;\"><strong><span class=\"title\">eJosh is easy To Customize</span></strong></span></p>\r\n<div class=\"space\"><br /></div>\r\n<div class=\"space\">Lorem\r\nipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy\r\nnibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.\r\nUt wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper\r\nsuscipit Ut wisi. Ut wisi enim ad minim veniam.</div>", :is_processing_reqd => false)

    PageSection.create(:display_name => "building_complete_solution", :title => "building complete solution", :content => "<p><img src=\"/system/images/5/small_thumb/building.jpg\" border=\"0\" alt=\"image\" width=\"35\" height=\"33\" style=\"float: left;\" /><span style=\"color: #888888; font-size: x-small;\"><strong></strong></span></p>\r\n<p><span style=\"color: #888888; font-size: xx-small;\"><strong><span class=\"title\">Building a complete solution was never so easy</span></strong></span></p>\r\n<p>&nbsp;</p>\r\n<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam\r\nnonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat\r\nvolutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation\r\nullamcorper suscipit Ut wisi. Ut wisi enim ad minim veniam.</p>", :is_processing_reqd => false)

    PageSection.create(:display_name => "feature1", :title => "feature1", :content => "<p><img src=\"/system/images/6/small_thumb/feature.jpg\" border=\"0\" alt=\"image\" width=\"50\" height=\"34\" style=\"float: left;\" /><span style=\"color: #888888; font-size: x-small;\"><strong></strong></span></p>\r\n<p><span style=\"color: #888888; font-size: x-small;\"><strong></strong></span></p>\r\n<p>&nbsp;<span style=\"color: #888888; font-size: x-small;\"><strong><span class=\"title\">Feature 1</span></strong></span></p>\r\n<p>&nbsp;</p>\r\n<p>Lorem\r\nipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy\r\nnibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.\r\nUt wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper\r\nsuscipit Ut wisi. Ut wisi enim ad minim veniam.</p>", :is_processing_reqd => false)

    PageSection.create(:display_name => "feature2", :title => "feature2", :content => "<p><img src=\"/system/images/7/small_thumb/feature1.jpg\" border=\"0\" alt=\"image\" width=\"43\" height=\"45\" style=\"float: left;\" /><span style=\"color: #888888; font-size: x-small;\"><strong><span class=\"title\">&nbsp; Feature 2</span></strong></span></p>\r\n<p>&nbsp;</p>\r\n<p>&nbsp;</p>\r\n<p>Lorem\r\nipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy\r\nnibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.\r\nUt wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper\r\nsuscipit Ut wisi. Ut wisi enim ad minim veniam.</p>", :is_processing_reqd => false)

    PageSection.create(:display_name => "About_us", :title => "About us", :content => "<p><img src=\"/system/images/8/small_thumb/about.jpg\" border=\"0\" alt=\"image\" width=\"50\" height=\"48\" style=\"float: left;\" /><span style=\"color: #888888; font-size: x-small;\"><strong><span class=\"title\">&nbsp; </span></strong></span></p>\r\n<p>&nbsp;&nbsp; <span style=\"color: #888888; font-size: x-small;\"><strong><span class=\"title\">About Us</span></strong></span><br /><br /></p>\r\n<p>&nbsp;</p>\r\n<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam\r\nnonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat\r\nvolutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation\r\nullamcorper suscipit Ut wisi. Ut wisi enim ad minim veniam.<br /><br /> Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam\r\nnonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat\r\nvolutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation\r\nullamcorper suscipit Ut wisi. Ut wisi enim ad minim veniam. Lorem ipsum\r\ndolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh\r\neuismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut\r\nwisi enim ad minim veniam, quis nostrud exerci tation ullamcorper\r\nsuscipit Ut wisi. Ut wisi enim ad minim veniam.<br /><br /> Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam\r\nnonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat\r\nvolutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation\r\nullamcorper suscipit Ut wisi. Ut wisi enim ad minim veniam.Lorem ipsum\r\ndolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh\r\neuismod tincidunt ut laoreet dolore magna aliquam erat volutpat.<br /><br /> Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam\r\nnonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat\r\nvolutpat. Ut wisi enim ad minim veniam, quis nostrud exerci.</p>", :is_processing_reqd => false)
  end

  def self.down
  end
end
